In [42]:
import pandas as pd
import numpy as np

In [43]:
def cargar_archivos():
    ruta = r"C:\Users\david\Documents\M5 challenge"

    df_sales_validation = pd.read_csv(ruta +"\sales_train_validation.csv")
    df_calendar = pd.read_csv(ruta+ "\calendar.csv")
    df_sell = pd.read_csv(ruta+"\sell_prices.csv")
    
    
    return df_sales_validation, df_calendar, df_sell
df_sales_validation, df_calendar, df_sell = cargar_archivos()

In [44]:
def formato_sales(df_sales_validation):
    # Convertir columnas de identidad a tipo 'category' y columnas de dias a tipo 'int16'

    columnas_identidad = ["id", "item_id", "dept_id", "cat_id", "store_id", "state_id"]
    columnas_dias = [col for col in df_sales_validation.columns if col.startswith("d_")]

    for col in columnas_identidad:
        df_sales_validation[col] = df_sales_validation[col].astype("category")

    df_sales_validation[columnas_dias] = df_sales_validation[columnas_dias].astype(np.int16)

    return df_sales_validation
df_sales_validation = formato_sales(df_sales_validation)

In [45]:
df_sales_validation.head()

,id,item_id,dept_id,cat_id,store_id,state_id,d_1,d_2,d_3,d_4,...,d_1904,d_1905,d_1906,d_1907,d_1908,d_1909,d_1910,d_1911,d_1912,d_1913
0,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,1,3,0,1,1,1,3,0,1,1
1,HOBBIES_1_002_CA_1_validation,HOBBIES_1_002,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2,HOBBIES_1_003_CA_1_validation,HOBBIES_1_003,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,2,1,2,1,1,1,0,1,1,1
3,HOBBIES_1_004_CA_1_validation,HOBBIES_1_004,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,1,0,5,4,1,0,1,3,7,2
4,HOBBIES_1_005_CA_1_validation,HOBBIES_1_005,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,2,1,1,0,1,1,2,2,2,4

In [46]:
df_sales_validation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30490 entries, 0 to 30489
Columns: 1919 entries, id to d_1913
dtypes: category(6), int16(1913)
memory usage: 112.8 MB

In [47]:
def formato_calendar(df_calendar):
    # Convertir date a tipo 'datetime', rellenar Nans con 'No event' y convertir a tipo 'category', eliminar columnas innecesarias

    df_calendar["date"] = pd.to_datetime(df_calendar["date"], format="%Y-%m-%d",errors="coerce")

    columnas_eventos = ["event_name_1", "event_type_1", "event_name_2", "event_type_2"]
    for col in columnas_eventos:
        df_calendar[col] = df_calendar[col].fillna("No event").astype("category")

    columnnas_string = ["weekday", "d"]
    for col in columnnas_string:
        df_calendar[col] = df_calendar[col].astype("category")

    df_calendar = df_calendar.drop(columns=["wday", "month", "year"])


    return df_calendar
df_calendar = formato_calendar(df_calendar)

In [48]:
df_calendar.head()

,date,wm_yr_wk,weekday,d,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI
0,2011-01-29,11101,Saturday,d_1,No event,No event,No event,No event,0,0,0
1,2011-01-30,11101,Sunday,d_2,No event,No event,No event,No event,0,0,0
2,2011-01-31,11101,Monday,d_3,No event,No event,No event,No event,0,0,0
3,2011-02-01,11101,Tuesday,d_4,No event,No event,No event,No event,1,1,0
4,2011-02-02,11101,Wednesday,d_5,No event,No event,No event,No event,1,0,1

In [49]:
df_calendar.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1969 entries, 0 to 1968
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          1969 non-null   datetime64[ns]
 1   wm_yr_wk      1969 non-null   int64
 2   weekday       1969 non-null   category
 3   d             1969 non-null   category
 4   event_name_1  1969 non-null   category
 5   event_type_1  1969 non-null   category
 6   event_name_2  1969 non-null   category
 7   event_type_2  1969 non-null   category
 8   snap_CA       1969 non-null   int64
 9   snap_TX       1969 non-null   int64
 10  snap_WI       1969 non-null   int64
dtypes: category(6), datetime64[ns](1), int64(4)
memory usage: 172.6 KB

In [50]:
def formato_prices(df_sell):
    # Convertir columnas de identidad a tipo 'category'

    columnas_texto = ["item_id", "store_id"]
    for col in columnas_texto:
        df_sell[col] = df_sell[col].astype("category")

    return df_sell
df_sell = formato_prices(df_sell)

In [51]:
df_sell.head()

  store_id        item_id  wm_yr_wk  sell_price
0     CA_1  HOBBIES_1_001     11325        9.58
1     CA_1  HOBBIES_1_001     11326        9.58
2     CA_1  HOBBIES_1_001     11327        8.26
3     CA_1  HOBBIES_1_001     11328        8.26
4     CA_1  HOBBIES_1_001     11329        8.26

In [52]:
df_sell.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6841121 entries, 0 to 6841120
Data columns (total 4 columns):
 #   Column      Dtype
---  ------      -----
 0   store_id    category
 1   item_id     category
 2   wm_yr_wk    int64
 3   sell_price  float64
dtypes: category(2), float64(1), int64(1)
memory usage: 124.0 MB